version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf

  fastapi:
    container_name: fastapi
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8001:8000

networks:
  custom:
    driver: bridge